<?php
define('VITE_SITE_ANIMATION', '%VITE_SITE_ANIMATION_ENV%');
define('VITE_SITE_SMTP_USER', '%VITE_SITE_SMTP_USER_ENV%');
define('VITE_SITE_SMTP_PASS', '%VITE_SITE_SMTP_PASS_ENV%');
define('VITE_SITE_SMTP_HOST', '%VITE_SITE_SMTP_HOST_ENV%');
define('VITE_SITE_SMTP_PORT', '%VITE_SITE_SMTP_PORT_ENV%');
define('VITE_SITE_SMTP_SECURE', '%VITE_SITE_SMTP_SECURE_ENV%');
define('VITE_SITE_SMTP_FROM', '%VITE_SITE_SMTP_FROM_ENV%');
define('VITE_SITE_SMTP_FROM_NAME', '%VITE_SITE_SMTP_FROM_NAME_ENV%');
define('VITE_SITE_MAILGUN_API', '%VITE_SITE_MAILGUN_API_ENV%');
define('VITE_SITE_MAILGUN_DOMAIN', '%VITE_SITE_MAILGUN_DOMAIN_ENV%');
define('VITE_SITE_TURNSTILE_KEY', '%VITE_SITE_TURNSTILE_KEY_ENV%');
define('VITE_SITE_TURNSTILE_SECRET', '%VITE_SITE_TURNSTILE_SECRET_ENV%');
